-- Backup and Migrate (Drupal) MySQL Dump
-- Backup and Migrate Version: 7.x-3.x
-- http://drupal.org/project/backup_migrate
-- Drupal Version: 7.43
-- http://drupal.org/
--
-- Generation Time: Tue, 14 Jun 2016 17:48:45 -0300
-- MySQL Version: 5.5.49-0ubuntu0.12.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=NO_AUTO_VALUE_ON_ZERO */;

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET NAMES utf8;

DROP TABLE IF EXISTS `field_data_field_birthday`;
CREATE TABLE `field_data_field_birthday` (   `entity_type` varchar(128) NOT NULL DEFAULT '' COMMENT 'The entity type this data is attached to',   `bundle` varchar(128) NOT NULL DEFAULT '' COMMENT 'The field instance bundle to which this row belongs, used when deleting a field instance',   `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'A boolean indicating whether this data item has been deleted',   `entity_id` int(10) unsigned NOT NULL COMMENT 'The entity id this data is attached to',   `revision_id` int(10) unsigned DEFAULT NULL COMMENT 'The entity revision id this data is attached to, or NULL if the entity type is not versioned',   `language` varchar(32) NOT NULL DEFAULT '' COMMENT 'The language for this data item.',   `delta` int(10) unsigned NOT NULL COMMENT 'The sequence number for this data item, used for multi-value fields',   `field_birthday_value` datetime DEFAULT NULL,   PRIMARY KEY (`entity_type`,`entity_id`,`deleted`,`delta`,`language`),   KEY `entity_type` (`entity_type`),   KEY `bundle` (`bundle`),   KEY `deleted` (`deleted`),   KEY `entity_id` (`entity_id`),   KEY `revision_id` (`revision_id`),   KEY `language` (`language`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Data storage for field 22 (field_birthday)';
INSERT INTO `field_data_field_birthday` VALUES ('user','user','0','3','3','und','0','1982-08-03 00:00:00'),('user','user','0','4','4','und','0','2000-01-01 00:00:00'),('user','user','0','5','5','und','0','2000-01-01 00:00:00'),('user','user','0','6','6','und','0','2000-01-01 00:00:00');
DROP TABLE IF EXISTS `field_data_field_fullname`;
CREATE TABLE `field_data_field_fullname` (   `entity_type` varchar(128) NOT NULL DEFAULT '' COMMENT 'The entity type this data is attached to',   `bundle` varchar(128) NOT NULL DEFAULT '' COMMENT 'The field instance bundle to which this row belongs, used when deleting a field instance',   `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'A boolean indicating whether this data item has been deleted',   `entity_id` int(10) unsigned NOT NULL COMMENT 'The entity id this data is attached to',   `revision_id` int(10) unsigned DEFAULT NULL COMMENT 'The entity revision id this data is attached to, or NULL if the entity type is not versioned',   `language` varchar(32) NOT NULL DEFAULT '' COMMENT 'The language for this data item.',   `delta` int(10) unsigned NOT NULL COMMENT 'The sequence number for this data item, used for multi-value fields',   `field_fullname_value` varchar(255) DEFAULT NULL,   `field_fullname_format` varchar(255) DEFAULT NULL,   PRIMARY KEY (`entity_type`,`entity_id`,`deleted`,`delta`,`language`),   KEY `entity_type` (`entity_type`),   KEY `bundle` (`bundle`),   KEY `deleted` (`deleted`),   KEY `entity_id` (`entity_id`),   KEY `revision_id` (`revision_id`),   KEY `language` (`language`),   KEY `field_fullname_format` (`field_fullname_format`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Data storage for field 24 (field_fullname)';
INSERT INTO `field_data_field_fullname` VALUES ('user','user','0','3','3','und','0','Ramon Magnus',null),('user','user','0','4','4','und','0','Robot4Addresses',null),('user','user','0','5','5','und','0','@placeowner',null),('user','user','0','6','6','und','0','@ncardowner',null);
DROP TABLE IF EXISTS `field_data_field_gender`;
CREATE TABLE `field_data_field_gender` (   `entity_type` varchar(128) NOT NULL DEFAULT '' COMMENT 'The entity type this data is attached to',   `bundle` varchar(128) NOT NULL DEFAULT '' COMMENT 'The field instance bundle to which this row belongs, used when deleting a field instance',   `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'A boolean indicating whether this data item has been deleted',   `entity_id` int(10) unsigned NOT NULL COMMENT 'The entity id this data is attached to',   `revision_id` int(10) unsigned DEFAULT NULL COMMENT 'The entity revision id this data is attached to, or NULL if the entity type is not versioned',   `language` varchar(32) NOT NULL DEFAULT '' COMMENT 'The language for this data item.',   `delta` int(10) unsigned NOT NULL COMMENT 'The sequence number for this data item, used for multi-value fields',   `field_gender_value` varchar(255) DEFAULT NULL,   PRIMARY KEY (`entity_type`,`entity_id`,`deleted`,`delta`,`language`),   KEY `entity_type` (`entity_type`),   KEY `bundle` (`bundle`),   KEY `deleted` (`deleted`),   KEY `entity_id` (`entity_id`),   KEY `revision_id` (`revision_id`),   KEY `language` (`language`),   KEY `field_gender_value` (`field_gender_value`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Data storage for field 25 (field_gender)';
INSERT INTO `field_data_field_gender` VALUES ('user','user','0','3','3','und','0','male'),('user','user','0','4','4','und','0','none'),('user','user','0','5','5','und','0','none'),('user','user','0','6','6','und','0','none');
DROP TABLE IF EXISTS `field_data_field_nickname`;
CREATE TABLE `field_data_field_nickname` (   `entity_type` varchar(128) NOT NULL DEFAULT '' COMMENT 'The entity type this data is attached to',   `bundle` varchar(128) NOT NULL DEFAULT '' COMMENT 'The field instance bundle to which this row belongs, used when deleting a field instance',   `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'A boolean indicating whether this data item has been deleted',   `entity_id` int(10) unsigned NOT NULL COMMENT 'The entity id this data is attached to',   `revision_id` int(10) unsigned DEFAULT NULL COMMENT 'The entity revision id this data is attached to, or NULL if the entity type is not versioned',   `language` varchar(32) NOT NULL DEFAULT '' COMMENT 'The language for this data item.',   `delta` int(10) unsigned NOT NULL COMMENT 'The sequence number for this data item, used for multi-value fields',   `field_nickname_value` varchar(255) DEFAULT NULL,   `field_nickname_format` varchar(255) DEFAULT NULL,   PRIMARY KEY (`entity_type`,`entity_id`,`deleted`,`delta`,`language`),   KEY `entity_type` (`entity_type`),   KEY `bundle` (`bundle`),   KEY `deleted` (`deleted`),   KEY `entity_id` (`entity_id`),   KEY `revision_id` (`revision_id`),   KEY `language` (`language`),   KEY `field_nickname_format` (`field_nickname_format`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Data storage for field 28 (field_nickname)';
INSERT INTO `field_data_field_nickname` VALUES ('user','user','0','3','3','und','0','3magnus',null),('user','user','0','4','4','und','0','Robot4Addresses',null),('user','user','0','5','5','und','0','@placeowner',null),('user','user','0','6','6','und','0','@ncardowner',null);
DROP TABLE IF EXISTS `field_revision_field_birthday`;
CREATE TABLE `field_revision_field_birthday` (   `entity_type` varchar(128) NOT NULL DEFAULT '' COMMENT 'The entity type this data is attached to',   `bundle` varchar(128) NOT NULL DEFAULT '' COMMENT 'The field instance bundle to which this row belongs, used when deleting a field instance',   `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'A boolean indicating whether this data item has been deleted',   `entity_id` int(10) unsigned NOT NULL COMMENT 'The entity id this data is attached to',   `revision_id` int(10) unsigned NOT NULL COMMENT 'The entity revision id this data is attached to',   `language` varchar(32) NOT NULL DEFAULT '' COMMENT 'The language for this data item.',   `delta` int(10) unsigned NOT NULL COMMENT 'The sequence number for this data item, used for multi-value fields',   `field_birthday_value` datetime DEFAULT NULL,   PRIMARY KEY (`entity_type`,`entity_id`,`revision_id`,`deleted`,`delta`,`language`),   KEY `entity_type` (`entity_type`),   KEY `bundle` (`bundle`),   KEY `deleted` (`deleted`),   KEY `entity_id` (`entity_id`),   KEY `revision_id` (`revision_id`),   KEY `language` (`language`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Revision archive storage for field 22 (field_birthday)';
INSERT INTO `field_revision_field_birthday` VALUES ('user','user','0','3','3','und','0','1982-08-03 00:00:00'),('user','user','0','4','4','und','0','2000-01-01 00:00:00'),('user','user','0','5','5','und','0','2000-01-01 00:00:00'),('user','user','0','6','6','und','0','2000-01-01 00:00:00');
DROP TABLE IF EXISTS `field_revision_field_fullname`;
CREATE TABLE `field_revision_field_fullname` (   `entity_type` varchar(128) NOT NULL DEFAULT '' COMMENT 'The entity type this data is attached to',   `bundle` varchar(128) NOT NULL DEFAULT '' COMMENT 'The field instance bundle to which this row belongs, used when deleting a field instance',   `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'A boolean indicating whether this data item has been deleted',   `entity_id` int(10) unsigned NOT NULL COMMENT 'The entity id this data is attached to',   `revision_id` int(10) unsigned NOT NULL COMMENT 'The entity revision id this data is attached to',   `language` varchar(32) NOT NULL DEFAULT '' COMMENT 'The language for this data item.',   `delta` int(10) unsigned NOT NULL COMMENT 'The sequence number for this data item, used for multi-value fields',   `field_fullname_value` varchar(255) DEFAULT NULL,   `field_fullname_format` varchar(255) DEFAULT NULL,   PRIMARY KEY (`entity_type`,`entity_id`,`revision_id`,`deleted`,`delta`,`language`),   KEY `entity_type` (`entity_type`),   KEY `bundle` (`bundle`),   KEY `deleted` (`deleted`),   KEY `entity_id` (`entity_id`),   KEY `revision_id` (`revision_id`),   KEY `language` (`language`),   KEY `field_fullname_format` (`field_fullname_format`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Revision archive storage for field 24 (field_fullname)';
INSERT INTO `field_revision_field_fullname` VALUES ('user','user','0','3','3','und','0','Ramon Magnus',null),('user','user','0','4','4','und','0','Robot4Addresses',null),('user','user','0','5','5','und','0','@placeowner',null),('user','user','0','6','6','und','0','@ncardowner',null);
DROP TABLE IF EXISTS `field_revision_field_gender`;
CREATE TABLE `field_revision_field_gender` (   `entity_type` varchar(128) NOT NULL DEFAULT '' COMMENT 'The entity type this data is attached to',   `bundle` varchar(128) NOT NULL DEFAULT '' COMMENT 'The field instance bundle to which this row belongs, used when deleting a field instance',   `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'A boolean indicating whether this data item has been deleted',   `entity_id` int(10) unsigned NOT NULL COMMENT 'The entity id this data is attached to',   `revision_id` int(10) unsigned NOT NULL COMMENT 'The entity revision id this data is attached to',   `language` varchar(32) NOT NULL DEFAULT '' COMMENT 'The language for this data item.',   `delta` int(10) unsigned NOT NULL COMMENT 'The sequence number for this data item, used for multi-value fields',   `field_gender_value` varchar(255) DEFAULT NULL,   PRIMARY KEY (`entity_type`,`entity_id`,`revision_id`,`deleted`,`delta`,`language`),   KEY `entity_type` (`entity_type`),   KEY `bundle` (`bundle`),   KEY `deleted` (`deleted`),   KEY `entity_id` (`entity_id`),   KEY `revision_id` (`revision_id`),   KEY `language` (`language`),   KEY `field_gender_value` (`field_gender_value`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Revision archive storage for field 25 (field_gender)';
INSERT INTO `field_revision_field_gender` VALUES ('user','user','0','3','3','und','0','male'),('user','user','0','4','4','und','0','none'),('user','user','0','5','5','und','0','none'),('user','user','0','6','6','und','0','none');
DROP TABLE IF EXISTS `field_revision_field_nickname`;
CREATE TABLE `field_revision_field_nickname` (   `entity_type` varchar(128) NOT NULL DEFAULT '' COMMENT 'The entity type this data is attached to',   `bundle` varchar(128) NOT NULL DEFAULT '' COMMENT 'The field instance bundle to which this row belongs, used when deleting a field instance',   `deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'A boolean indicating whether this data item has been deleted',   `entity_id` int(10) unsigned NOT NULL COMMENT 'The entity id this data is attached to',   `revision_id` int(10) unsigned NOT NULL COMMENT 'The entity revision id this data is attached to',   `language` varchar(32) NOT NULL DEFAULT '' COMMENT 'The language for this data item.',   `delta` int(10) unsigned NOT NULL COMMENT 'The sequence number for this data item, used for multi-value fields',   `field_nickname_value` varchar(255) DEFAULT NULL,   `field_nickname_format` varchar(255) DEFAULT NULL,   PRIMARY KEY (`entity_type`,`entity_id`,`revision_id`,`deleted`,`delta`,`language`),   KEY `entity_type` (`entity_type`),   KEY `bundle` (`bundle`),   KEY `deleted` (`deleted`),   KEY `entity_id` (`entity_id`),   KEY `revision_id` (`revision_id`),   KEY `language` (`language`),   KEY `field_nickname_format` (`field_nickname_format`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Revision archive storage for field 28 (field_nickname)';
INSERT INTO `field_revision_field_nickname` VALUES ('user','user','0','3','3','und','0','Ramon',null),('user','user','0','4','4','und','0','Robot4Addresses',null),('user','user','0','5','5','und','0','@placeowner',null),('user','user','0','6','6','und','0','@ncardowner',null);
DROP TABLE IF EXISTS `history`;
CREATE TABLE `history` (   `uid` int(11) NOT NULL DEFAULT '0' COMMENT 'The users.uid that read the node nid.',   `nid` int(11) NOT NULL DEFAULT '0' COMMENT 'The node.nid that was read.',   `timestamp` int(11) NOT NULL DEFAULT '0' COMMENT 'The Unix timestamp at which the read occurred.',   PRIMARY KEY (`uid`,`nid`),   KEY `nid` (`nid`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='A record of which users have read which nodes.';
INSERT INTO `history` VALUES ('1','1','1465220195'),('1','2','1465220202'),('1','3','1465310573'),('1','4','1465325649'),('1','6','1465309070'),('1','8','1465309971');
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (   `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Primary Key: Unique user ID.',   `name` varchar(60) NOT NULL DEFAULT '' COMMENT 'Unique user name.',   `pass` varchar(128) NOT NULL DEFAULT '' COMMENT 'User’s password (hashed).',   `mail` varchar(254) DEFAULT '' COMMENT 'User’s e-mail address.',   `theme` varchar(255) NOT NULL DEFAULT '' COMMENT 'User’s default theme.',   `signature` varchar(255) NOT NULL DEFAULT '' COMMENT 'User’s signature.',   `signature_format` varchar(255) DEFAULT NULL COMMENT 'The filter_format.format of the signature.',   `created` int(11) NOT NULL DEFAULT '0' COMMENT 'Timestamp for when user was created.',   `access` int(11) NOT NULL DEFAULT '0' COMMENT 'Timestamp for previous time user accessed the site.',   `login` int(11) NOT NULL DEFAULT '0' COMMENT 'Timestamp for user’s last login.',   `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'Whether the user is active(1) or blocked(0).',   `timezone` varchar(32) DEFAULT NULL COMMENT 'User’s time zone.',   `language` varchar(12) NOT NULL DEFAULT '' COMMENT 'User’s default language.',   `picture` int(11) NOT NULL DEFAULT '0' COMMENT 'Foreign key: file_managed.fid of user’s picture.',   `init` varchar(254) DEFAULT '' COMMENT 'E-mail address used for initial account creation.',   `data` longblob COMMENT 'A serialized array of name value pairs that are related to the user. Any form values posted during user edit are stored and are loaded into the $user object during user_load(). Use of this field is discouraged and it will likely disappear in a future...',   PRIMARY KEY (`uid`),   UNIQUE KEY `name` (`name`),   KEY `access` (`access`),   KEY `created` (`created`),   KEY `mail` (`mail`),   KEY `picture` (`picture`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Stores user data.';
INSERT INTO `users` VALUES ('0','','','','','',null,'0','0','0','0',null,'','0','',null),('1','user1','$S$D.KyVVfR7YwVpJMv1Q/XsFY2iIqLDYxT/c3pr8zzkNO3X9TYXjRG','user1@t3cno.com','','',null,'1464866962','1465937246','1465331762','1','America/Sao_Paulo','','0','user1@t3cno.com','b:0;'),('3','3magnus','$S$D.KyVVfR7YwVpJMv1Q/XsFY2iIqLDYxT/c3pr8zzkNO3X9TYXjRG','3magnus@t3cno.com','','','simplest_html','1464874644','0','0','1','America/Sao_Paulo','es','0','3magnus@t3cno.com','a:1:{s:7:"contact";i:1;}'),('4','robot4addresses','$S$D.KyVVfR7YwVpJMv1Q/XsFY2iIqLDYxT/c3pr8zzkNO3X9TYXjRG','robot4addresses@t3cno.com','','','simplest_html','1464874733','0','0','1','America/Sao_Paulo','en','0','robot4addresses@t3cno.com','a:1:{s:7:"contact";i:1;}'),('5','@placeowner','$S$D.KyVVfR7YwVpJMv1Q/XsFY2iIqLDYxT/c3pr8zzkNO3X9TYXjRG','placeowner@t3cno.com','','','simplest_html','1464890595','0','0','1','America/Sao_Paulo','en','0','placeowner@t3cno.com','a:1:{s:7:"contact";i:1;}'),('6','@ncardowner','$S$DZA4kp9Shk046msZDAkXRszj7IJWN4hY.ZaSwim21dG75rVIaHK5','ncardowner@t3cno.com','','','simplest_html','1464891473','0','0','1','America/Sao_Paulo','pt-br','0','ncardowner@t3cno.com','a:1:{s:7:"contact";i:1;}');
DROP TABLE IF EXISTS `users_roles`;
CREATE TABLE `users_roles` (   `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Primary Key: users.uid for user.',   `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Primary Key: role.rid for role.',   PRIMARY KEY (`uid`,`rid`),   KEY `rid` (`rid`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Maps users to roles.';
INSERT INTO `users_roles` VALUES ('6','4'),('5','6'),('3','7'),('4','8'),('5','9'),('6','9');

  
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
